//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPersonView
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Name { get; set; }
        public string HPNumber { get; set; }
        public string OfficeNumber { get; set; }
        public string EmailAddress { get; set; }
        public string StatusName { get; set; }
        public string Remark { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
