//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ContactPersons = new HashSet<ContactPerson>();
            this.Sites = new HashSet<Site>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public Nullable<int> StatusFk { get; set; }
        public int CreatedByFk { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<ContactPerson> ContactPersons { get; set; }
        public virtual Status Status { get; set; }
        public virtual WebUser WebUser { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
