//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.EmailAttachments = new HashSet<EmailAttachment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TicketFk { get; set; }
        public string TicketNo { get; set; }
        public string UID { get; set; }
        public System.DateTime ReceivedTime { get; set; }
        public string ToAddress { get; set; }
        public string FromAddress { get; set; }
        public string CCAddress { get; set; }
        public string Subject { get; set; }
        public string EmailContent { get; set; }
        public string EmailLocation { get; set; }
        public bool Attachment { get; set; }
        public Nullable<bool> Ignore { get; set; }
        public string Remark { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<EmailAttachment> EmailAttachments { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
