//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupView
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public bool ViewAbleByCustomer { get; set; }
        public string EmailAccount { get; set; }
        public string Status { get; set; }
    }
}
