//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public Right()
        {
            this.RoleRights = new HashSet<RoleRight>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Remark { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<RoleRight> RoleRights { get; set; }
    }
}
