//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteView
    {
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public string SiteAddress { get; set; }
        public int SiteStatusId { get; set; }
        public string SiteStatus { get; set; }
        public string CustomerName { get; set; }
        public string Country { get; set; }
        public Nullable<int> CountryFk { get; set; }
        public int CustomerId { get; set; }
    }
}
