//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Roles = new HashSet<Role>();
            this.WebUsers = new HashSet<WebUser>();
            this.ContactPersons = new HashSet<ContactPerson>();
            this.Customers = new HashSet<Customer>();
            this.Sites = new HashSet<Site>();
        }
    
        public int Id { get; set; }
        public string StatusName { get; set; }
        public string Remark { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<WebUser> WebUsers { get; set; }
        public virtual ICollection<ContactPerson> ContactPersons { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
