//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketLog
    {
        public int Id { get; set; }
        public string TicketNo { get; set; }
        public string TicketOwner { get; set; }
        public bool NotifyOwner { get; set; }
        public Nullable<int> AssignTosUer { get; set; }
        public Nullable<int> AssignTosGroup { get; set; }
        public string TicketType { get; set; }
        public string Priority { get; set; }
        public string ReportMethod { get; set; }
        public bool FileUpload { get; set; }
        public string Customer { get; set; }
        public string ContactPerson { get; set; }
        public bool NotifyContact { get; set; }
        public string ContactNo { get; set; }
        public string ContactEmail { get; set; }
        public string SiteName { get; set; }
        public string SiteAddress { get; set; }
        public string TicketDetails { get; set; }
        public string TicketStatus { get; set; }
        public bool OnSite { get; set; }
        public string Comment { get; set; }
        public int Duration { get; set; }
        public string Resolution { get; set; }
        public string Subscribers { get; set; }
        public string AdditionField1 { get; set; }
        public string AdditionField2 { get; set; }
        public string AdditionField3 { get; set; }
        public string AdditionField4 { get; set; }
        public string AdditionField5 { get; set; }
        public string RecordingId { get; set; }
        public string CreatedBy { get; set; }
        public string Remark { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
