//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Emails = new HashSet<Email>();
            this.FileUploads = new HashSet<FileUpload>();
        }
    
        public int Id { get; set; }
        public string TicketNo { get; set; }
        public System.DateTime ReceivedTime { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public int TicketOwnerFk { get; set; }
        public bool NotifyOwner { get; set; }
        public Nullable<int> AssignTosUerFk { get; set; }
        public Nullable<int> AssigntoGroupFk { get; set; }
        public int TicketTypeFk { get; set; }
        public int PriorityFk { get; set; }
        public int TicketClassificationFk { get; set; }
        public int ReportMethodFk { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public string ContactEmail { get; set; }
        public bool NotifyCustomer { get; set; }
        public string SiteName { get; set; }
        public string SiteAddress { get; set; }
        public Nullable<int> CustomerFk { get; set; }
        public string TicketDetails { get; set; }
        public int TicketStatusFk { get; set; }
        public Nullable<int> ResolutionFk { get; set; }
        public string Resolution { get; set; }
        public bool FileUpload { get; set; }
        public bool OnSite { get; set; }
        public bool TicketClosed { get; set; }
        public Nullable<int> KIVDuration { get; set; }
        public int TicketDuration { get; set; }
        public string Comment { get; set; }
        public string Escalation { get; set; }
        public string Subscribers { get; set; }
        public string AdditionField1 { get; set; }
        public string AdditionField2 { get; set; }
        public string AdditionField3 { get; set; }
        public string AdditionField4 { get; set; }
        public string AdditionField5 { get; set; }
        public int CreatedByFk { get; set; }
        public string Remark { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<FileUpload> FileUploads { get; set; }
        public virtual Group Group { get; set; }
        public virtual TicketClassificationName TicketClassificationName { get; set; }
        public virtual TicketPriority TicketPriority { get; set; }
        public virtual TicketReportMethod TicketReportMethod { get; set; }
        public virtual TicketResolutionType TicketResolutionType { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
