//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webzyEntities : DbContext
    {
        public webzyEntities()
            : base("name=webzyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<CountryLog> CountryLogs { get; set; }
        public DbSet<Right> Rights { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleLog> RoleLogs { get; set; }
        public DbSet<RoleRight> RoleRights { get; set; }
        public DbSet<RoleRightLog> RoleRightLogs { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<WebUser> WebUsers { get; set; }
        public DbSet<WebUserLog> WebUserLogs { get; set; }
        public DbSet<WebUserRole> WebUserRoles { get; set; }
        public DbSet<WebUserRoleLog> WebUserRoleLogs { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<UserGroup> UserGroups { get; set; }
        public DbSet<GroupView> GroupViews { get; set; }
        public DbSet<GroupLog> GroupLogs { get; set; }
        public DbSet<WebUserView> WebUserViews { get; set; }
        public DbSet<UserGroupLog> UserGroupLogs { get; set; }
        public DbSet<UserRightsView> UserRightsViews { get; set; }
        public DbSet<ContactPerson> ContactPersons { get; set; }
        public DbSet<ContactPersonLog> ContactPersonLogs { get; set; }
        public DbSet<CustomerLog> CustomerLogs { get; set; }
        public DbSet<EmailAttachment> EmailAttachments { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<FileUpload> FileUploads { get; set; }
        public DbSet<LDAPSetting> LDAPSettings { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<SiteLog> SiteLogs { get; set; }
        public DbSet<TicketClassificationName> TicketClassificationNames { get; set; }
        public DbSet<TicketLog> TicketLogs { get; set; }
        public DbSet<TicketPriority> TicketPriorities { get; set; }
        public DbSet<TicketReportMethod> TicketReportMethods { get; set; }
        public DbSet<TicketResolutionType> TicketResolutionTypes { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TicketStatu> TicketStatus { get; set; }
        public DbSet<TicketType> TicketTypes { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerView> CustomerViews { get; set; }
        public DbSet<SiteView> SiteViews { get; set; }
    }
}
